FROM hashicorp/terraform:1.9.7 as terraform

FROM registry.access.redhat.com/ubi8/ubi:8.10

ENV SUMMARY="UBI based Sumo Logic Kubernetes Setup" \
    DESCRIPTION="UBI based setup image for the Sumo Logic Kubernetes Collection"

ENV COLLECTION_VERSION=v4.6.1
ENV MONITORS_VERSION=v1.2.4
ARG TARGETPLATFORM

RUN dnf update -y \
    && dnf install -y \
    bash \
    curl \
    jq \
    git \
    && dnf clean all \
    && groupadd -g 1000 setup \
    && adduser -u 1000 -g setup setup \
    && mkdir /terraform /scripts /monitors \
    && chown -R setup:setup /terraform /scripts /monitors

COPY --from=terraform /bin/terraform /usr/local/bin/terraform

USER setup
RUN cd /terraform/ \
    && curl -O https://raw.githubusercontent.com/SumoLogic/sumologic-kubernetes-collection/${COLLECTION_VERSION}/deploy/helm/sumologic/conf/setup/main.tf \
    && terraform init \
    && rm main.tf
RUN cd /monitors/ \
    && git clone https://github.com/SumoLogic/terraform-sumologic-sumo-logic-monitor.git \
    && cd terraform-sumologic-sumo-logic-monitor \
    && git checkout ${MONITORS_VERSION} \
    && cd .. \
    && cp terraform-sumologic-sumo-logic-monitor/monitor_packages/kubernetes/* . \
    && terraform init -input=false || terraform init -input=false -upgrade \
    && rm -rf terraform-sumologic-sumo-logic-monitor

ARG BUILD_TAG=latest
ENV TAG=$BUILD_TAG

LABEL name="Sumo Logic Kubernetes Setup" \
    vendor="Sumo Logic" \
    version="${BUILD_TAG}" \
    release="1" \
    summary="$SUMMARY" \
    description="$DESCRIPTION" \
    io.k8s.description="$DESCRIPTION" \
    maintainer="opensource-collection-team@sumologic.com"

ADD LICENSE \
    /licenses/LICENSE

WORKDIR /terraform/
