name: Dev builds

on:
  push:
    branches:
      - main
      - "dev-build/*"

jobs:
  setup-image:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.1.0

      - name: Set up Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Show Buildx platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Login to Open Source ECR
        run: make login
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Login to Docker Hub
        run: |
          docker login \
            --username ${{ secrets.DOCKERHUB_LOGIN }} \
            --password ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push image to Open Source ECR
        run: make build-push-multiplatform

      - name: Build and push UBI image to Open Source ECR
        run: make build-push-multiplatform \
          DOCKERFILE=Dockerfile-ubi \
          TAG_SUFFIX=-ubi \
          PLATFORMS=linux/amd64,linux/arm64

      - name: Build and push image to Docker Hub
        run: |-
          make build-push-multiplatform \
          REPO_URL=sumologic/kubernetes-setup

      - name: Build and push UBI image to Docker Hub
        run: |-
          make build-push-multiplatform \
          REPO_URL=sumologic/kubernetes-setup \
          DOCKERFILE=Dockerfile-ubi \
          TAG_SUFFIX=-ubi \
          PLATFORMS=linux/amd64,linux/arm64
