name: PRs checks

on:
  pull_request:
    branches:
      - main

jobs:
  setup-image:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Build setup image
        run: make build
      - name: Build UBI based setup image
        run: make build \
          DOCKERFILE=Dockerfile-ubi \
          TAG_SUFFIX=-ubi
